# Generated by Django 4.2.23 on 2025-07-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_budget_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                default="expense",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
