# Generated by Django 4.2.23 on 2025-07-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_transaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="budget", name="month", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("Income", "Income"), ("Expense", "Expense")],
                default="Expense",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("Income", "Income"), ("Expense", "Expense")], max_length=10
            ),
        ),
    ]
