# Generated by Django 4.2.23 on 2025-07-14 17:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0005_alter_budget_amount"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budget", unique_together={("user", "month", "year")},
        ),
        migrations.RemoveField(model_name="budget", name="category",),
    ]
