# Generated by Django 5.2.7 on 2025-10-07 00:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('401K', '401(k)'), ('IRA', 'Traditional IRA'), ('ROTH_IRA', 'Roth IRA'), ('403B', '403(b)'), ('SEP_IRA', 'SEP-IRA'), ('SIMPLE_IRA', 'SIMPLE IRA'), ('PENSION', 'Pension'), ('OTHER', 'Other')], max_length=20)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employer_match_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Employer match percentage', max_digits=5, null=True)),
                ('vesting_schedule', models.TextField(blank=True, help_text='Vesting schedule details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'account_name')},
            },
        ),
        migrations.CreateModel(
            name='RetirementContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('EMPLOYEE', 'Employee Contribution'), ('EMPLOYER', 'Employer Match'), ('ROLLOVER', 'Rollover'), ('CATCH_UP', 'Catch-up Contribution')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution_date', models.DateField()),
                ('tax_year', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retirement.retirementaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-contribution_date'],
            },
        ),
        migrations.CreateModel(
            name='RetirementGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_retirement_age', models.IntegerField(default=65)),
                ('target_retirement_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_age', models.IntegerField()),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_annual_return', models.DecimalField(decimal_places=2, default=Decimal('7.00'), help_text='Expected annual return percentage', max_digits=5)),
                ('inflation_rate', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Expected inflation rate percentage', max_digits=5)),
                ('retirement_income_replacement', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Percentage of current income needed in retirement', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetirementProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(max_length=100)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_return_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('years_to_retirement', models.IntegerField()),
                ('projected_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialSecurityEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_monthly_benefit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('full_retirement_age', models.IntegerField(default=67)),
                ('early_retirement_benefit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('delayed_retirement_benefit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('last_updated', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
